### ISSUE TITLE
Plotting in cmsl1t

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#3]
As discussed on various occasions we want to keep the code that creates the histograms and the plotting code separate.
As such no serious plotting has been implemented yet.
We need to define what we expect from the plotting and possibly how to configure it from the outside (e.g. YAML config).

@benkrikler

**Comment by benkrikler** [comment]
This is something we might want to come back to actually.  
In #37 I entangled the concepts a bit since although the histogram collection class is now somewhat separate, the histograms needed by the plotter are actually owned and managed by the plotter. So perhaps we want to separate them again, to be able to adhere to this idea

**Comment by kreczko** [comment]
First version implemented in #38 and #37. The spirit of this issue is still valid and needs to be evaluated for the next stage.
