### ISSUE TITLE
Batch submission

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#58]
A showstopper to using this analysis software on a large scale is its restriction to only run locally.

As such we need a way to submit things as the legacy macros do.
We need the same interface for `bsub`, `qsub` and htcondor with the latter being the priority.

This code should not be part of this repository since it greatly overlaps with efforts in FAST and other places.

So, for this repository we probably need something like `RemoteTask`.

**Comment by benkrikler** [comment]
Batch submission should now be implemented after:
 * #59 - Add ability to reload histograms
 * #60 - Add initial script to submit jobs to the batch system (via bsub)
 * #62 - Add Docker testing environment for job submission 
 * #63 - Fix up batch submission system 

I think, therefore, the general nature of this issue is met, however, we do not support htcondor submission systems in this framework.  I think then we should close this and add an extending issue to add htcondor support.
